YemekApp/Controllers/HesaplarController.cs
using System.Globalization;
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using System.Text;
using DataAccess.Contexts;
using DataAccess.Entities;
using DataAccess.Enums;
using Microsoft.EntityFrameworkCore;

namespace MvcWebUI.Controllers
{
    public class HesaplarController : Controller
    {
        private readonly IHesapService _hesapService;

        private readonly IUlkeService _ulkeService;
        private readonly ISehirService _sehirService;

        public HesaplarController(IHesapService hesapService, IUlkeService ulkeService, ISehirService sehirService)
        {
            _hesapService = hesapService;
            _ulkeService = ulkeService;
            _sehirService = sehirService;
        }

        public IActionResult Giris()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Giris(KullaniciGirisModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _hesapService.Giris(model);
                if (result.IsSuccessful)
                {
                    List<Claim> claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, result.Data.KullaniciAdi),
                        new Claim(ClaimTypes.Role, result.Data.RolAdiDisplay),
                        //new Claim(ClaimTypes.Email, result.Data.KullaniciDetayi.Eposta),
                        new Claim(ClaimTypes.Sid, result.Data.Id.ToString())
                    };
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(model);
        }

        public async Task<IActionResult> Cikis()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult YetkisizIslem()
        {
            return View("Hata", "Bu işlem için yetkiniz bulunmamaktadır!");
        }

        public IActionResult Kayit()
        {
            var result = _ulkeService.UlkeleriGetir();
            if (result.IsSuccessful)
                ViewBag.UlkeId = new SelectList(result.Data, "Id", "Adi");
            else
                ViewBag.Mesaj = result.Message;
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Kayit(KullaniciKayitModel model)
        {
            if (ModelState.IsValid)
            {
                var kayitSonuc = _hesapService.Kayit(model);
                if (kayitSonuc.IsSuccessful)
                    return RedirectToAction(nameof(Giris));
                ViewBag.Mesaj = kayitSonuc.Message;
            }
            var ulkeSonuc = _ulkeService.UlkeleriGetir();
            ViewBag.UlkeId = new SelectList(ulkeSonuc.Data, "Id", "Adi", model.KullaniciDetayi.UlkeId ?? -1); // eğer UlkeId null'sa -1 kullan
            var sehirSonuc = _sehirService.SehirleriGetir(model.KullaniciDetayi.UlkeId ?? -1);
            ViewBag.SehirId = new SelectList(sehirSonuc.Data, "Id", "Adi", model.KullaniciDetayi.SehirId ?? -1);
            return View(model);
        }
    }
}

YemekApp/Controllers/RollerController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MvcWebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RollerController : Controller
    {
        private readonly IRolService _rolService;

        public RollerController(IRolService rolService)
        {
            _rolService = rolService;
        }

        // GET: Roller
        public IActionResult Index()
        {
            var result = _rolService.RolleriGetir();
            ViewBag.Sonuc = result.Message;
            return View(result.Data);
        }

        // GET: Roller/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return View("Hata", "Id gereklidir!");
            }
            var result = _rolService.RolGetir(id.Value);
            if (!result.IsSuccessful)
            {
                ViewBag.Sonuc = result.Message;
            }
            return View(result.Data);
        }

        // GET: Roller/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roller/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RolModel rol)
        {
            ModelState.Remove(nameof(rol.Id));
            if (ModelState.IsValid)
            {
                var result = _rolService.Add(rol);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            return View(rol);
        }

        // GET: Roller/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("Hata", "Id gereklidir!");
            }
            var result = _rolService.RolGetir(id.Value);
            if (!result.IsSuccessful)
            {
                return View("Hata", result.Message);
            }
            return View(result.Data);
        }

        // POST: Roller/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(RolModel rol)
        {
            if (ModelState.IsValid)
            {
                var result = _rolService.Update(rol);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            return View(rol);
        }

        // GET: Roller/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return View("Hata", "Id gereklidir!");
            }
            var result = _rolService.Delete(id.Value);
            TempData["Sonuc"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
    }
}

YemekApp/Controllers/UlkelerController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MvcWebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UlkelerController : Controller
    {
        private readonly IUlkeService _ulkeService;

        public UlkelerController(IUlkeService ulkeService)
        {
            _ulkeService = ulkeService;
        }

        // GET: Ulkeler
        public IActionResult Index()
        {
            return View(_ulkeService.Query().ToList());
        }

        // GET: Ulkeler/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ulkeler/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(UlkeModel ulke)
        {
            if (ModelState.IsValid)
            {
                var result = _ulkeService.Add(ulke);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            return View(ulke);
        }

        // GET: Ulkeler/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("Hata", "Id gereklidir!");
            }
            UlkeModel ulke = _ulkeService.Query().SingleOrDefault(u => u.Id == id);
            if (ulke == null)
            {
                return View("Hata", "Kayıt bulunamadı!");
            }
            return View(ulke);
        }

        // POST: Ulkeler/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(UlkeModel ulke)
        {
            if (ModelState.IsValid)
            {
                var result = _ulkeService.Update(ulke);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            return View(ulke);
        }

        // GET: Ulkeler/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return View("Hata", "Id gereklidir!");
            }
            var result = _ulkeService.Delete(id.Value);
            TempData["Sonuc"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
    }
}

YemekApp/Controllers/YemekController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Contexts;
using DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Business.Models;
using Business.Services;
using Business.Services.Bases;

namespace YemekApp.Controllers
{
    [Authorize]
    public class YemekController : Controller
    {
        private readonly IYemekTarifiService _yemekTarifiService;
        private readonly IMalzemeService _malzemeService;

        public YemekController(IYemekTarifiService yemekTarifiService, IMalzemeService malzemeService)
        {
            _yemekTarifiService = yemekTarifiService;
            _malzemeService = malzemeService;
        }

        [AllowAnonymous] 
        public IActionResult Index()
        {
            return View(_yemekTarifiService.Query().ToList());
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
                return View("Hata", "Id gereklidir!");
            YemekTarifiModel model = _yemekTarifiService.Query().SingleOrDefault(u => u.Id == id.Value);
            if (model == null)
                return View("Hata", "Kayıt bulunamadı!");
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            List<MalzemeModel> malzemeler = _malzemeService.Query().ToList();
            ViewBag.MalzemeId = new SelectList(malzemeler, "Id", "Adi");

            YemekTarifiModel model = new YemekTarifiModel()
            {
                Adi = "Deneme",
                Tarif = "Deneme",
                 MalzemeId = 2
            };

            var group1 = new SelectListGroup() { Name = "Malzemeler" };

            ViewBag.Malzeme = new List<SelectListItem>()
            {
                new SelectListItem(){Text = "Muz", Value = model.MalzemeId == null ? "1":model.MalzemeId.ToString(), Group = group1},
                new SelectListItem(){Text = "Süt", Value = "2", Group = group1},
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]        
        public IActionResult Create(YemekTarifiModel yemekTarifi)
        {
            if (ModelState.IsValid)
            {                
                var result = _yemekTarifiService.Add(yemekTarifi);
                if (result.IsSuccessful)
                {
                    TempData["Success"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            ViewBag.MalzemeId = new SelectList(_malzemeService.Query().ToList(), "Id", "Adi", yemekTarifi.MalzemeId);

            return View(yemekTarifi);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return View("Hata", "Id gereklidir!");
            YemekTarifiModel model = _yemekTarifiService.Query().SingleOrDefault(u => u.Id == id.Value);
            if (model == null)
                return View("Hata", "Kayıt bulunamadı!");
            ViewBag.MalzemeId = new SelectList(_malzemeService.Query().ToList(), "Id", "Adi", model.MalzemeId);

            return View(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(YemekTarifiModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _yemekTarifiService.Update(model);
                if (result.IsSuccessful)
                {
                    TempData["Success"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            ViewBag.MalzemeId = new SelectList(_malzemeService.Query().ToList(), "Id", "Adi", model.MalzemeId);

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return View("Hata", "Id gereklidir!");
            YemekTarifiModel model = _yemekTarifiService.Query().SingleOrDefault(u => u.Id == id.Value);
            if (model == null)
                return View("Hata", "Kayıt bulunamadı!");
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmed(int id)
        {
            var result = _yemekTarifiService.Delete(id);

            YemekTarifiModel model = new YemekTarifiModel()
            {
                Id = id,
            };

            TempData["Success"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
    }
}

YemekApp/Views/Shared/Hata.cshtml
@model string 

<h2 class="text-danger">Hata!</h2>

@if (string.IsNullOrWhiteSpace(Model))
{
    <p class="text-danger">İşlem sırasında hata meydana geldi!</p>
}
else
{
    <p class="text-danger">@Model</p>
}

YemekApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>E-Ticaret | @ViewData["Title"]</title>
    @*<title>@AppSettings.Baslik | @ViewData["Title"]</title>*@

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <!-- icon kütüphanesi: -->
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/main.css" rel="stylesheet" />
</head>
<body>
    <div class="wrapper">
        <nav id="sidebar">

            @*<div class="sidebar-header">*@
            <div class="sidebar-header baslik">

                <h3>E-Ticaret</h3>
                @*<a asp-action="Index" asp-controller="Home" class="a-sidebar"><h5><i class="fas fa-shopping-basket"></i> @AppSettings.Baslik</h5></a>*@

            </div>
            <ul class="list-unstyled components">
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Yemek" class="a-sidebar"><i class="fas fa-clipboard-list"></i> Yemek Tarifleri</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            @* HTML *@
                            @*<a class="a-navbar" href="/Database/Seed"> Verileri Sıfırla</a>*@

                            @* HTML Helper Klasik MVC ve MVC Core *@
                            @*@Html.ActionLink("Verileri Sıfırla", "Seed", "Database", null, new { @class = "a-navbar" })*@

                            @* Tag Helper MVC Core *@
                            @*<a asp-action="Seed" asp-controller="Database" class="a-navbar">Verileri Sıfırla</a>*@
                        </li>
                    }
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Malzemeler" class="a-sidebar"><i class="fas fa-clipboard-list"></i> Malzemeler</a>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Kullanici" class="a-sidebar"><i class="fas fa-users"></i> Kullanıcılar</a>
                        </li>
                    }
                }
            </ul>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <ul class="list-unstyled admin">
                    <p>Tanımlar</p>
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Roller" class="a-sidebar"><i class="fas fa-bars"></i> Roller</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Ulkeler" class="a-sidebar"><i class="fas fa-bars"></i> Ülkeler</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Sehirler" class="a-sidebar"><i class="fas fa-bars"></i> Şehirler</a>
                    </li>
                </ul>

                <ul class="list-unstyled admin">
                    <p>Raporlar</p>
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="UrunlerRapor" class="a-sidebar"><i class="fas fa-archive"></i> Ürünler Raporu</a>
                    </li>
                </ul>
            }
        </nav>
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler navbar-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon navbar-span"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            @*<a class="a-navbar" href="#"> Ana Sayfa</a>*@
                        </li>
                    </ul>
                    <div class="navbar-text">
                        <ul class="navbar-nav me-auto">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="a-navbar" asp-action="Kayit" asp-controller="Hesaplar"><i class="far fa-save"></i> Kayıt</a>
                                </li>
                                <li class="nav-item">
                                    <a class="a-navbar" asp-action="Giris" asp-controller="Hesaplar"><i class="fas fa-sign-in-alt"></i> Giriş</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <div class="div-navbar">
                                        <span class="s-navbar"><i class="fas fa-user"></i> @User.Identity.Name</span>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="a-navbar" asp-action="Cikis" asp-controller="Hesaplar"><i class="fas fa-sign-out-alt"></i> Çıkış</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container">
                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- icon kütüphanesi: -->
    <script src="~/lib/font-awesome/js/all.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

YemekApp/Views/Shared/_Sonuc.cshtml
@{
    string result;
    string color;
}

@if (ViewBag.Sonuc != null)
{
    result = ViewBag.Sonuc.ToString();
    color = "success";
    if (result.EndsWith("!"))
    {
        color = "danger";
    }
    <p class="text-@color">
        @result
    </p>
}

@if (TempData["Sonuc"] != null)
{
    result = TempData["Sonuc"].ToString();
    color = "success";
    if (result.EndsWith("!"))
    {
        color = "danger";
    }
    <p class="text-@color">
        @result
    </p>
}